version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run:
          - name: Successful build
          - when: on_success
          - command: MIX_ENV=docs mix deps.get
          - command: MIX_ENV=docs mix inch.report
